name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-fish:
    name: Check Fish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.launchpad.net:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@939056556c2bfd55b3e2c039e9d34b237c0b9d5b # v2.1.11
      - uses: fish-shop/indent-check@82531182f7b5431da27f590467d4774bab1c1eec # v2.2.102
      - uses: fish-shop/syntax-check@27c94ee9456333e716f92b50e0f99effd768e0ee # v2.2.100
      - uses: fish-shop/install-plugin@8e0e56ba1ac1a37098ec523878f8f1c2d0306177 # v2.3.104
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@b9427c3b6e670abc1c70c41a3cf46b8f2b67c5d5 # v2.3.104
