name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-fish:
    name: Check Fish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allow-sudo: false
          allowed-endpoints: >
            _http._tcp.azure.archive.ubuntu.com:443
            _https._tcp.esm.ubuntu.com:443
            _https._tcp.motd.ubuntu.com:443
            _https._tcp.packages.microsoft.com:443
            _https._tcp.ppa.launchpadcontent.net:443
            api.github.com:443
            api.launchpad.net:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@b93bca74575a36e725e51679b1c18748784a6afc # v2.1.19
      - uses: fish-shop/indent-check@6557200fc43e12e1eb2966da3e01cade9eb7e2ee # v2.2.110
      - uses: fish-shop/syntax-check@f9a5452f25a01b3fb1212ed02c04b3617faca4ce # v2.2.108
      - uses: fish-shop/install-plugin@51b7b99773c98be71c046ccaaa7d586d37fbb68a # v2.3.112
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@99b60b58172fa166abdfc78077cb0fbaac099064 # v2.3.112
