name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-fish:
    name: Check Fish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: block
          allow-sudo: false
          allowed-endpoints: >
            _http._tcp.azure.archive.ubuntu.com:443
            _https._tcp.esm.ubuntu.com:443
            _https._tcp.motd.ubuntu.com:443
            _https._tcp.packages.microsoft.com:443
            _https._tcp.ppa.launchpadcontent.net:443
            api.github.com:443
            api.launchpad.net:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@fe67e809bbaa60cd967a424635fd5baed7e59e63 # v2.1.13
      - uses: fish-shop/indent-check@40900dadd983f5747a6e5fc4d80f9e3d5ce64c6e # v2.2.104
      - uses: fish-shop/syntax-check@7566d3ae834a316caf3adc590743ef5d90416c0a # v2.2.102
      - uses: fish-shop/install-plugin@54ee6568771da6525643d7f97d371a1b117a0aff # v2.3.106
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@b8a56010ff103dd7ebe8e068bae0a7e70c1c3ad8 # v2.3.106
