name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

jobs:
  zizmor:
    uses: halostatue/halostatue/.github/workflows/zizmor.yml@2e1187207c35d23f064bce4592d87c2c7ca7e334 # v1.0.2
    permissions:
      security-events: write
      contents: read
      actions: read
