name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

jobs:
  zizmor:
    uses: halostatue/halostatue/.github/workflows/zizmor.yml@428ed193b60d646b13590d314188760d72a9ca39 # v1.0.3
    permissions:
      security-events: write
      contents: read
      actions: read
