name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

jobs:
  zizmor:
    uses: halostatue/halostatue/.github/workflows/zizmor.yml@0fa19a3bec5383af45c771b04f06a0f4c0bc3bbd # v1.0.1
    permissions:
      security-events: write
      contents: read
      actions: read
