name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

jobs:
  zizmor:
    uses: halostatue/halostatue/.github/workflows/zizmor.yml@bff7f39eab9abb98033c9968e9ecfbf6057a17f8 # v1.0.0
    permissions:
      security-events: write
      contents: read
      actions: read
