name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

jobs:
  zizmor:
    uses: halostatue/halostatue/.github/workflows/zizmor.yml@411de20fbd855c17e77a371fd3e1074247a25c48 # v1.0.4
    permissions:
      security-events: write
      contents: read
      actions: read
